### ISSUE TITLE
unknown module “iautils" imported in unpack_datafiles function

### ISSUE THREAD

**Issue by xuhengdada** [chime-frb-open-data/chime-frb-open-data#5]
An unknown module name "iautils" is imported in chime_intensity. unpack_datafiles, line 171.

Some file may be lost in your package, I guess

**Comment by chitrangpatel** [comment]
Thanks for catching this. We'll fix it ASAP.

**Comment by shinybrar** [comment]
@xuhengdada 
Currently all CHIME/FRB data files have the same resolution, ~1ms but in the future data files can potentially have multiple downsampling rates in the same dataset. `iautils` is currently an internal library which handles this edge case. In the current release you will never hit that line of code, so it should not break anything.

**Comment by mef51** [comment]
Hi @shinybrar I am currently hitting that block of code for burst 180917 (which is from the [data provided for 180914](https://www.canfar.net/citation/landing?doi=19.0005)) since this burst seems to have a time resolution of ~2ms according to the paper. Is it possible to add the `iautils` library? 

You can circumvent this block by setting `downsample=False` but then I get the following error:
`MemoryError: Unable to allocate 128. MiB for an array with shape (16384, 2048) and data type float32` which might be due to my system, not sure yet.

**Comment by mef51** [comment]
I can bypass the problematic code and see the burst by just forcing [it into the main branch](https://github.com/chime-frb-open-data/chime-frb-open-data/blob/master/cfod/chime_intensity.py#L153), is there any disadvantage to this? I can't tell what the purpose of the other branch is 
![image](https://user-images.githubusercontent.com/1703141/94066376-69dc2180-fdba-11ea-9ffe-c4740ac95ee3.png)

**Comment by shinybrar** [comment]
@mef51 There is no disadvantage, you can make a PR to master
